### ISSUE TITLE
Material about DAO👇🏻

### ISSUE THREAD

**Issue by Vakurin** [New-Connection/newconnection-dao#1]

**Comment by hokage229** [comment]
https://github.com/PatrickAlphaC/dao-template

**Comment by hokage229** [comment]
https://www.youtube.com/watch?v=i5-3Wx_BrSA

**Comment by hokage229** [comment]
Openzeppelin - стандарты:

- https://docs.openzeppelin.com/contracts/4.x/governance
- https://docs.openzeppelin.com/contracts/4.x/api/governance

**Comment by hokage229** [comment]
Openzeppelin - стандарты:

- https://docs.openzeppelin.com/contracts/4.x/governance
- https://docs.openzeppelin.com/contracts/4.x/api/governance
