### ISSUE TITLE
Simple organisation contract 

### ISSUE THREAD

**Issue by Vakurin** [New-Connection/newconnection-dao#3]

**Comment by hokage229** [comment]
ДАО редактироватть
1) Аватарка
2) Кавер изображение
3) Доп поля
-----
* В смарте добавить поле добавления ссылки на json.
* Какие участники есть в дао?????
* Чтобы можно было приглашать по адресу в ДАО 
* А потом сделать клейм
-----------------------
При создании голосовалки
1) Добавить чтобы была ссылка на json
