### ISSUE TITLE
Tests for DAO

### ISSUE THREAD

**Issue by Vakurin** [New-Connection/newconnection-dao#4]

**Comment by hokage229** [comment]
Тесты для создание proposal:

1. Можно создать если достаточно threshold
2. Не может создать если недостаточно threshold
3. Может создать после делегирование ERC20Votes токенов

**Comment by hokage229** [comment]
Тесты для voting:

1. Может проголосовать создатель предложения. state after: Succeeded
2. Проголосовав  с 0 голосами (на момент снапшота). state after: Defeated
3. Никто не голосовал. state after: Defeated
4. Проголосовал, но кворум не достигнут. state after: Defeated
5. Проголосовал с votePower  равной точно необходимой для того, чтобы кворум был достигнут

**Comment by hokage229** [comment]
Тесты для execute:

1. execute после голосование ЗА
2. revert если голосование не закончено
3. revert если голосование ПРОТИВ
4. revert если не проголосовали

**Comment by hokage229** [comment]
Пример теста
`it("should ...", async function () {
      // some code
});`

- тестировать через  `yarn hardhat test` или `npx hardhat test` (можно `hh test` если установлен Shorthand -https://hardhat.org/guides/shorthand.html)
- для удобства можно добавлять к тесту .only (например. `it.only("should ...`) чтобы тестировать каждый тест отдельно
